 sudo: required
 language: generic 
 services: 
   - docker 
 before_install: 
   - docker build -t pp9119/docker-react -f Dockerfile.dev .
 script:
   - docker run  pp9119/docker-react npm run test -- --coverge
