FROM node:alpine

WORKDIR '/app'

COPY --chown=node:node package.json .
#RUN npm install --unsafe-perm=true --allow-root

RUN npm install 

COPY --chown=node:node . .

RUN chmod 777 .
USER node 
CMD ["npm","run", "start"]
