FROM node:alpine

WORKDIR '/app'

COPY --chown=node:node package.json .
#RUN npm install --unsafe-perm=true --allow-root

#RUN chown node:node .
RUN npm install 

COPY --chown=node:node . .
RUN chown node:node ./node_modules/
RUN chmod 777 .
USER node 
CMD ["npm","run", "start"]
